server {
    server_name chat.huhuhu.top;
    client_max_body_size 80m;

    location / {
        if ($http_x_couplechat_proxy_key != "__PROXY_KEY__") { return 403; }

        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host hoo66.top;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    listen [::1]:10443 ssl;
    listen 127.0.0.1:10443 ssl;
    ssl_certificate /etc/letsencrypt/live/chat.huhuhu.top/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chat.huhuhu.top/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
