disabled_rules:
  - trailing_whitespace
  - identifier_name
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - large_tuple
  - cyclomatic_complexity
  - nesting
  - force_cast
  - force_try
  - comma
  - type_name
  - trailing_comma
  - function_parameter_count
  - implicit_optional_initialization
  - vertical_whitespace
  - modifier_order
  - statement_position

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - first_where
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - toggle_bool

excluded:
  - build
  - build-artifacts
  - DerivedData
  - node_modules
  - server
  - .build
  - .github
