export const AI_DEBUG_PAGE = String.raw`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>大橘 AI 光路台</title>
  <script src="/socket.io/socket.io.js"></script>
  <style>
    *{box-sizing:border-box}body{margin:0;font:14px "Microsoft YaHei UI",system-ui;background:#f3f6f8;color:#16202a;height:100vh;overflow:hidden}
    header{height:58px;display:flex;align-items:center;padding:0 18px;background:#fff;border-bottom:1px solid #dce3e8;font-weight:700}header small{margin-left:10px;color:#718092;font:11px Consolas}#health{margin-left:auto;color:#4b806b;font-weight:400}
    main{height:calc(100vh - 58px);display:grid;grid-template-columns:44% 56%;gap:1px;background:#dce3e8}.panel{background:#fff;min-height:0}.chat{display:grid;grid-template-rows:auto 1fr auto}.trace{display:grid;grid-template-rows:auto auto 1fr}
    .toolbar,.trace-head{padding:12px 14px;border-bottom:1px solid #dce3e8;display:flex;gap:8px;align-items:center}.toolbar button,.trace-tabs button{border:1px solid #dce3e8;background:#fff;border-radius:7px;padding:7px 10px}.toolbar button.active,.trace-tabs button.active{border-color:#356681;background:#eaf2f6}.toolbar label{margin-left:auto;color:#718092}
    #messages,#traceBody,#memoryBody{overflow:auto;padding:16px}.msg{max-width:84%;margin:0 0 14px}.msg.self{margin-left:auto}.msg.ai{margin-left:12px}.who,.time{font-size:10px;color:#718092;margin:4px 7px}.self .time{text-align:right}.bubble{white-space:pre-wrap;line-height:1.55;padding:10px 12px;border:1px solid #dce3e8;border-radius:12px;background:#fff}.self .bubble{background:#356681;color:#fff;border-color:#356681}.ai .bubble{border-left:3px solid #e47a36}
    .composer{padding:12px;border-top:1px solid #dce3e8}.composer textarea{width:100%;min-height:72px;padding:10px;border:1px solid #cfd8df;border-radius:9px;resize:vertical}.composer div{display:flex;justify-content:space-between;margin-top:8px;color:#718092}.composer button{border:0;border-radius:7px;background:#16202a;color:#fff;padding:8px 15px}
    .trace-head h2{margin:0;font-size:16px}.trace-head span{margin-left:auto;color:#718092}.view-switch{display:flex;gap:4px;margin-left:12px}.view-switch button{border:1px solid #dce3e8;background:#fff;border-radius:7px;padding:6px 10px}.view-switch button.active{background:#16202a;color:#fff}.trace-tabs{display:flex;gap:6px;padding:8px 12px;overflow:auto;border-bottom:1px solid #dce3e8}.trace-tabs button{flex:none;text-align:left;font-size:11px}.trace-tabs small{display:block;color:#718092;margin-top:3px}
    details{border:1px solid #dce3e8;border-radius:8px;margin-bottom:10px;background:#fff}summary{padding:10px 12px;font-weight:700;cursor:pointer}.payload{border-top:1px solid #edf0f2;padding:10px 12px}pre{margin:0;white-space:pre-wrap;word-break:break-word;font:11px/1.5 Consolas;color:#334454;max-height:440px;overflow:auto}
    #memoryPanel,#importPanel{display:grid;grid-template-rows:auto 1fr;min-height:0}.memory-filters{display:flex;gap:8px;padding:8px 12px;border-bottom:1px solid #dce3e8}.memory-filters select,.memory-filters button,.toolbar select{border:1px solid #dce3e8;background:#fff;border-radius:7px;padding:7px 9px}.memory-card{border:1px solid #dce3e8;border-radius:9px;margin-bottom:10px;padding:11px}.memory-card header{height:auto;padding:0;border:0;background:transparent}.memory-card .tags{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:7px}.tag{font:10px Consolas;background:#edf3f6;color:#426273;border-radius:5px;padding:3px 6px}.memory-card p{margin:6px 0;line-height:1.5}.memory-card small{color:#718092}.evidence{margin-top:8px;border-left:3px solid #a8cbbd;padding:6px 9px;background:#f7faf9;font-size:12px;white-space:pre-wrap}.danger{color:#a33!important;border-color:#d8aaa8!important}.hidden{display:none!important}
    #importBody{overflow:auto;padding:16px}.import-summary{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:12px}.metric{border:1px solid #dce3e8;border-radius:8px;padding:9px;background:#f8fafb}.metric b{display:block;font-size:18px}.run{border:1px solid #dce3e8;border-radius:8px;padding:10px;margin-bottom:8px}.progress{height:7px;background:#e8edf0;border-radius:5px;overflow:hidden;margin-top:7px}.progress i{display:block;height:100%;background:#4c8e78}.candidate-actions{display:flex;gap:7px;margin-top:9px}.candidate-actions button{border:1px solid #ccd7dd;background:#fff;border-radius:6px;padding:5px 9px}.approve{color:#287257!important;border-color:#91c0ae!important}
    dialog{border:0;border-radius:12px;padding:22px;width:min(520px,90vw)}dialog input{width:100%;margin:6px 0;padding:8px}dialog button{padding:8px 12px}.accounts{display:grid;grid-template-columns:1fr 1fr;gap:14px}.ok{color:#2f8064}
    @media(max-width:900px){body{overflow:auto;height:auto}main{height:auto;grid-template-columns:1fr}.panel{min-height:700px}}
  </style>
</head>
<body>
<header>大橘 AI 光路台 <small>LOCAL / AGENT + MCP + MEMORY</small><span id="health">等待登录</span></header>
<main>
  <section class="panel chat">
    <div class="toolbar"><button data-channel="couple" class="active">公聊</button><button data-channel="ai">AI 私聊</button><span id="senders"></span><select id="clearCount" title="清除条数"><option>20</option><option>50</option><option selected>100</option><option>200</option></select><button id="clearRecent" class="danger">清除最近聊天</button><label><input id="summon" type="checkbox" checked> 发送时召唤 @大橘</label></div>
    <div id="messages"></div>
    <div class="composer"><textarea id="input" placeholder="输入消息，Enter 发送，Shift + Enter 换行"></textarea><div><span id="hint">公聊消息会写入真实数据库</span><button id="send" disabled>发送</button></div></div>
  </section>
  <section class="panel trace">
    <div class="trace-head"><h2 id="panelTitle">本轮光路</h2><div class="view-switch"><button id="showTrace" class="active">光路</button><button id="showMemory">记忆</button><button id="showImport">迁移</button></div><span id="traceMeta">尚未选择</span></div>
    <div class="trace-tabs" id="traceTabs"></div>
    <div id="traceBody">发送一条召唤消息后，这里会显示 Agent、MCP 工具、输入和输出。</div>
    <div id="memoryPanel" class="hidden"><div class="memory-filters"><select id="memoryLayer"><option value="">全部层级</option><option value="fact">事实</option><option value="event">事件</option><option value="plan">计划</option><option value="state">状态</option><option value="relationship">关系</option><option value="insight">洞察</option></select><select id="memoryStatus"><option value="active">有效</option><option value="all">全部状态</option><option value="superseded">已替代</option><option value="retracted">已撤销</option><option value="completed">已完成</option><option value="cancelled">已取消</option><option value="expired">已过期</option></select><button id="refreshMemory">刷新记忆</button><button id="flushMemory">立即整理当前聊天</button></div><div id="memoryBody">点击“记忆”查看当前可见记忆。</div></div>
    <div id="importPanel" class="hidden"><div class="memory-filters"><select id="importStatus"><option value="needs_review" selected>待审核</option><option value="all">全部候选</option><option value="verified">已验证</option><option value="approved">已批准</option><option value="rejected">已拒绝</option><option value="published">已发布</option></select><button id="refreshImport">刷新进度</button><span>优先显示全部待审核项；批准只改变暂存状态，不会自动发布。</span></div><div id="importBody">点击“迁移”查看运行进度。</div></div>
  </section>
</main>
<dialog id="login"><h2>连接两位主人</h2><p>登录状态保存在本机浏览器，刷新页面不会重复输入密码。</p><div class="accounts" id="accounts"></div><p id="loginError"></p></dialog>
<dialog id="clearDialog"><h2>清除最近聊天</h2><p id="clearPrompt"></p><p>对应的上下文摘要会重置；失去全部原文证据的记忆会自动撤销。</p><div style="display:flex;justify-content:flex-end;gap:8px"><button id="cancelClear">取消</button><button id="confirmClear" class="danger">确认清除</button></div></dialog>
<script>
(()=>{
  const state={accounts:[],sessions:{},active:"",channel:"couple",messages:new Map(),traces:new Map(),selected:"",poll:null,traceVersion:"",view:"trace",importLast:0};
  const $=id=>document.getElementById(id), esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  const token=()=>state.sessions[state.active]?.token;
  async function api(url,options={}){const headers={...(options.headers||{})};if(token())headers.Authorization="Bearer "+token();const response=await fetch(url,{...options,headers});if(!response.ok)throw new Error("HTTP "+response.status);return response.json()}
  function persist(){const saved={};Object.entries(state.sessions).forEach(([username,session])=>saved[username]={token:session.token});localStorage.setItem("couplechat-ai-debug-sessions",JSON.stringify(saved))}
  function health(){const connected=Object.values(state.sessions).filter(session=>session.socket.connected).length;$("health").textContent=connected+" / "+state.accounts.length+" 个账号已连接";$("send").disabled=!token()}
  function renderSenders(){$("senders").innerHTML=state.accounts.map(account=>'<button data-sender="'+esc(account.username)+'" class="'+(state.active===account.username?'active':'')+'">'+esc(account.name)+'</button>').join("")}
  function connect(account,userToken){if(state.sessions[account.username])return;const socket=io({auth:{token:userToken}});state.sessions[account.username]={token:userToken,socket};if(!state.active)state.active=account.username;socket.on("connect",health);socket.on("disconnect",health);socket.on("message:new",message=>{if(message.channel===state.channel)upsert(message)});socket.on("message:recalled",message=>{if(message.channel===state.channel)upsert(message)});renderSenders();persist();health()}
  async function restore(){let saved={};try{saved=JSON.parse(localStorage.getItem("couplechat-ai-debug-sessions")||"{}")}catch{}for(const account of state.accounts){const item=saved[account.username];if(!item?.token)continue;try{await fetch("/api/me",{headers:{Authorization:"Bearer "+item.token}}).then(response=>{if(!response.ok)throw new Error()});connect(account,item.token)}catch{}}if(Object.keys(state.sessions).length===state.accounts.length){$("login").close();await loadMessages();startPolling()}else $("login").showModal()}
  function renderLogin(){$("accounts").innerHTML=state.accounts.map(account=>'<div id="account-'+esc(account.username)+'"><b>'+esc(account.name)+'</b><input type="password" id="password-'+esc(account.username)+'" placeholder="密码"><button data-login="'+esc(account.username)+'">登录</button></div>').join("")}
  async function login(username){const account=state.accounts.find(item=>item.username===username);try{const data=await api("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password:$("password-"+username).value})});connect(account,data.token);$("account-"+username).classList.add("ok");if(Object.keys(state.sessions).length===state.accounts.length){$("login").close();await loadMessages();startPolling()}}catch(error){$("loginError").textContent=error.message}}
  function upsert(message){state.messages.set(message.id,message);renderMessages()}
  function renderMessages(){const box=$("messages"),follow=box.scrollHeight-box.scrollTop-box.clientHeight<56,oldTop=box.scrollTop,list=[...state.messages.values()].sort((a,b)=>a.ts-b.ts);box.innerHTML=list.map(message=>{const ai=message.sender==="ai"||message.kind!=="user",self=message.sender===state.active;return '<article class="msg '+(ai?'ai':self?'self':'peer')+'"><div class="who">'+esc(ai?'大橘':message.senderName)+'</div><div class="bubble">'+esc(message.text||'['+message.type+']')+'</div><div class="time">'+new Date(message.ts).toLocaleTimeString("zh-CN",{hour12:false})+'</div></article>'}).join("");box.scrollTop=follow?box.scrollHeight:oldTop}
  async function loadMessages(){if(!token())return;const data=await api("/api/messages?channel="+state.channel+"&limit=100");state.messages.clear();data.list.forEach(message=>state.messages.set(message.id,message));renderMessages()}
  function requestClear(){if(!token()){$("hint").textContent="请先登录当前主人账号后再清除";$("login").showModal();return}const count=Number($("clearCount").value)||100;$("clearPrompt").textContent="将删除当前"+(state.channel==="couple"?"公聊":"AI 私聊")+"最近 "+count+" 条本机消息。";$("clearDialog").showModal()}
  async function confirmClear(){const count=Number($("clearCount").value)||100;$("confirmClear").disabled=true;$("clearPrompt").textContent="正在清除，请稍候…";try{const data=await api("/api/ai-debug/messages/recent",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({channel:state.channel,username:state.active,limit:count})});$("clearDialog").close();$("hint").textContent="已清除 "+data.deleted+" 条消息";await loadMessages();if(state.view==="memory")await loadMemory()}catch(error){$("clearPrompt").textContent="清除失败："+error.message}finally{$("confirmClear").disabled=false}}
  function renderTabs(){const list=[...state.traces.values()].sort((a,b)=>b.ts-a.ts).slice(0,12);$("traceTabs").innerHTML=list.map(trace=>'<button data-trace="'+esc(trace.id)+'" class="'+(trace.id===state.selected?'active':'')+'">'+esc(trace.requesterName+': '+(trace.question||'').slice(0,16))+'<small>'+new Date(trace.ts).toLocaleTimeString("zh-CN",{hour12:false})+'</small></button>').join("")}
  function block(title,value,open=false){return '<details '+(open?'open':'')+'><summary>'+title+'</summary><div class="payload"><pre>'+esc(JSON.stringify(value,null,2))+'</pre></div></details>'}
  function renderTrace(trace){const version=trace.id+"|"+trace.status+"|"+(trace.finishedTs||"")+"|"+JSON.stringify(trace.timings||{})+"|"+(trace.agent?.toolCalls?.length||0)+"|"+(trace.reply?.rawOutput?.length||0);if(state.traceVersion===version)return;const box=$("traceBody"),same=state.traceVersion.startsWith(trace.id+"|"),oldTop=box.scrollTop,open=[...box.querySelectorAll("details")].map(item=>item.open);$("traceMeta").textContent=trace.id+" · "+trace.channel+" · "+trace.status;box.innerHTML=block("01 Agent 与 MCP 工具",trace.agent||{waiting:true},true)+block("02 Agent Instructions",trace.prompt?.system||"等待生成")+block("03 Agent 初始输入",trace.prompt?.user||"等待生成")+block("04 最终输出",trace.reply||{waiting:true},true)+block("05 阶段耗时",trace.timings||{})+(trace.error?block("错误",trace.error,true):"");[...box.querySelectorAll("details")].forEach((item,index)=>{if(same&&open[index]!==undefined)item.open=open[index]});box.scrollTop=same?oldTop:0;state.traceVersion=version}
  function renderMemory(items){const box=$("memoryBody");if(!items.length){box.innerHTML="当前筛选下没有记忆。";return}box.innerHTML=items.map(item=>'<article class="memory-card"><header><div class="tags"><span class="tag">'+esc(item.layer)+'</span><span class="tag">'+esc(item.status)+'</span><span class="tag">'+esc(item.scope)+'</span><span class="tag">'+esc(item.category||"general")+'</span></div></header><p>'+esc(item.content)+'</p><small>主体 '+esc((item.subjects||[]).join(", ")||"-")+' · key '+esc(item.memoryKey)+' · 置信度 '+esc(item.confidence)+' · 重要度 '+esc(item.importance)+' · 更新 '+new Date(item.updatedAt).toLocaleString("zh-CN",{hour12:false})+'</small>'+(item.evidence||[]).map(e=>'<div class="evidence"><b>'+esc(e.sender)+' · '+new Date(e.message_ts).toLocaleString("zh-CN",{hour12:false})+' · '+esc(e.evidence_role)+'</b><br>'+esc(e.excerpt)+'</div>').join("")+'</article>').join("")}
  async function loadMemory(){if(!token())return;$("memoryBody").textContent="正在读取记忆…";try{const query=new URLSearchParams({channel:state.channel,username:state.active,status:$("memoryStatus").value,limit:"100"});if($("memoryLayer").value)query.set("layer",$("memoryLayer").value);const data=await api("/api/ai-debug/memory?"+query);renderMemory(data.items)}catch(error){$("memoryBody").textContent="读取失败："+error.message}}
  function importCard(item){const subjects=(()=>{try{return JSON.parse(item.subjects_json||"[]").join(", ")}catch{return "-"}})(),confidence=item.status==="rejected"?"—":item.confidence;return '<article class="memory-card"><div class="tags"><span class="tag">'+esc(item.layer)+'</span><span class="tag">'+esc(item.status)+'</span><span class="tag">'+esc(item.source_table)+'</span><span class="tag">'+esc(item.scope)+'</span></div><p>'+esc(item.content)+'</p><small>主体 '+esc(subjects||"-")+' · 置信度 '+esc(confidence)+' · 来源 '+esc(item.source_id)+'</small>'+(item.review_reason?'<p><small>'+esc(item.review_reason)+'</small></p>':'')+(item.evidence||[]).map(e=>'<div class="evidence"><b>'+esc(e.senderName||e.sender)+' · '+new Date(e.ts).toLocaleString("zh-CN",{hour12:false})+'</b><br>'+esc(e.text)+'</div>').join("")+(item.status==="needs_review"||item.status==="verified"?'<div class="candidate-actions"><button class="approve" data-decision="approve" data-id="'+esc(item.id)+'">批准</button><button class="danger" data-decision="reject" data-id="'+esc(item.id)+'">拒绝</button></div>':'')+'</article>'}
  function renderImport(data){const counts=data.counts||{},runs=data.runs||[];const running=runs.find(run=>run.status==="running");const metrics='<div class="import-summary"><div class="metric"><b>'+esc(running?running.processed_count:0)+'</b>本轮已处理</div><div class="metric"><b>'+esc(counts.needs_review||0)+'</b>待审核</div><div class="metric"><b>'+esc(counts.verified||0)+'</b>已验证</div><div class="metric"><b>'+esc(counts.rejected||0)+'</b>已拒绝</div><div class="metric"><b>'+esc(counts.published||0)+'</b>已发布</div></div>';const runHtml=runs.slice(0,4).map(run=>{const total=Number(JSON.parse(run.options_json||"{}").limit)||0,pct=total?Math.min(100,Math.round(Number(run.processed_count)*100/total)):0;return '<div class="run"><b>'+esc(run.source)+' · '+esc(run.status)+'</b> <small>'+esc(run.model)+' · '+esc(run.processed_count)+' / '+esc(total)+' · 候选 '+esc(run.candidate_count)+' · 错误 '+esc(run.error_count)+'</small><div class="progress"><i style="width:'+pct+'%"></i></div></div>'}).join("");$("importBody").innerHTML=metrics+runHtml+(data.candidates||[]).map(importCard).join("")}
  async function loadImport(force=false){if(!token())return;if(!force&&Date.now()-state.importLast<1800)return;state.importLast=Date.now();try{const data=await api("/api/ai-debug/memory/import?status="+encodeURIComponent($("importStatus").value)+"&limit=100");renderImport(data);const active=(data.runs||[]).find(run=>run.status==="running"),remaining=Number(data.counts?.needs_review||0);$("traceMeta").textContent=active?"正在迁移 · 已处理 "+active.processed_count:remaining?"还有 "+remaining+" 条待审核":"迁移审核已完成"}catch(error){$("importBody").textContent="读取迁移进度失败："+error.message}}
  async function decideImport(id,decision){try{await api("/api/ai-debug/memory/import/"+encodeURIComponent(id)+"/decision",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision})});state.importLast=0;await loadImport(true)}catch(error){$("traceMeta").textContent="审核失败："+error.message}}
  function switchView(view){state.view=view;const memory=view==="memory",migration=view==="import",trace=!memory&&!migration;$("showTrace").classList.toggle("active",trace);$("showMemory").classList.toggle("active",memory);$("showImport").classList.toggle("active",migration);$("traceTabs").classList.toggle("hidden",!trace);$("traceBody").classList.toggle("hidden",!trace);$("memoryPanel").classList.toggle("hidden",!memory);$("importPanel").classList.toggle("hidden",!migration);$("panelTitle").textContent=memory?"Memory 观察台":migration?"历史迁移":"本轮光路";$("traceMeta").textContent=memory?"当前频道 · "+state.channel:migration?"迁移暂存区":(state.selected||"尚未选择");if(memory)loadMemory();if(migration){state.importLast=0;loadImport(true)}}
  async function flushCurrentMemory(){if(!token())return;$("memoryBody").textContent="正在整理新消息…";try{await api("/api/ai-debug/memory/flush",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({channel:state.channel,username:state.active})});await loadMemory()}catch(error){$("memoryBody").textContent="整理失败："+error.message}}
  async function selectTrace(id){state.selected=id;renderTabs();try{const data=await api("/api/ai-debug/traces/"+encodeURIComponent(id));state.traces.set(id,data.trace);renderTrace(data.trace)}catch{}}
  async function poll(){if(!token())return;if(state.view==="import"){await loadImport();return}try{const data=await api("/api/ai-debug/traces?since="+(Date.now()-3600000));data.traces.forEach(trace=>state.traces.set(trace.id,trace));if(!state.selected&&data.traces[0])state.selected=data.traces[0].id;renderTabs();if(state.selected&&state.traces.has(state.selected))renderTrace(state.traces.get(state.selected))}catch{}}
  function startPolling(){clearInterval(state.poll);poll();state.poll=setInterval(poll,800)}
  function send(){const session=state.sessions[state.active];let text=$("input").value.trim();if(!session||!text)return;if(state.channel==="couple"&&$("summon").checked&&!text.includes("@大橘"))text="@大橘 "+text;session.socket.emit("message:send",{channel:state.channel,type:"text",text,clientId:"debug_"+Date.now()},result=>{if(result?.ok){$("input").value="";upsert(result.message);selectTrace(result.id)}else $("hint").textContent="发送失败"})}
  $("accounts").addEventListener("click",event=>{const username=event.target.getAttribute("data-login");if(username)login(username)});$("senders").addEventListener("click",event=>{const username=event.target.getAttribute("data-sender");if(username&&state.sessions[username]){state.active=username;renderSenders();loadMessages();poll();if(state.view==="memory")loadMemory()}});document.querySelector(".toolbar").addEventListener("click",event=>{const channel=event.target.getAttribute("data-channel");if(channel){state.channel=channel;document.querySelectorAll("[data-channel]").forEach(button=>button.classList.toggle("active",button.dataset.channel===channel));$("summon").disabled=channel!=="couple";loadMessages();if(state.view==="memory")loadMemory()}});$("traceTabs").addEventListener("click",event=>{const button=event.target.closest("[data-trace]");if(button)selectTrace(button.dataset.trace)});$("importBody").addEventListener("click",event=>{const button=event.target.closest("[data-decision]");if(button)decideImport(button.dataset.id,button.dataset.decision)});$("clearRecent").addEventListener("click",requestClear);$("cancelClear").addEventListener("click",()=>$("clearDialog").close());$("confirmClear").addEventListener("click",confirmClear);$("showTrace").addEventListener("click",()=>switchView("trace"));$("showMemory").addEventListener("click",()=>switchView("memory"));$("showImport").addEventListener("click",()=>switchView("import"));$("refreshMemory").addEventListener("click",loadMemory);$("flushMemory").addEventListener("click",flushCurrentMemory);$("refreshImport").addEventListener("click",()=>{state.importLast=0;loadImport(true)});$("importStatus").addEventListener("change",()=>{state.importLast=0;loadImport(true)});$("memoryLayer").addEventListener("change",loadMemory);$("memoryStatus").addEventListener("change",loadMemory);$("send").addEventListener("click",send);$("input").addEventListener("keydown",event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();send()}});
  fetch("/api/accounts").then(response=>response.json()).then(async accounts=>{state.accounts=accounts.slice(0,2);renderLogin();await restore();health()});
})();
</script>
</body>
</html>`;
